from typing import Dict, Optional

from app.engine.entities.talent_enum import Subclass, Talent


# Maps talent name → (max_points, tier, subclass_required_or_None)
CLERIC_TALENT_DEFS: Dict[str, tuple[int, int, Optional[str]]] = {
    # Tier 1
    Talent.SATIATED_SPELLS: (2, 1, None),
    Talent.HOLY_INTUITION: (2, 1, None),
    Talent.SEARING_LIGHT: (2, 1, None),
    Talent.SHIELD_OF_LIGHT: (2, 1, None),
    # Tier 2
    Talent.ENLIGHTENING_MEAL: (2, 2, None),
    Talent.RECALL_INSCRIPTION: (2, 2, None),
    Talent.SUNRAY: (2, 2, None),
    Talent.DIVINE_SENSE: (2, 2, None),
    Talent.BLESS: (2, 2, None),
    # Tier 3 — class
    Talent.CLEANSE: (3, 3, None),
    Talent.LIGHT_READING: (3, 3, None),
    # Tier 3 — Priest
    Talent.HOLY_LANCE: (3, 3, Subclass.PRIEST),
    Talent.HALLOWED_GROUND: (3, 3, Subclass.PRIEST),
    Talent.MNEMONIC_PRAYER: (3, 3, Subclass.PRIEST),
    # Tier 3 — Paladin
    Talent.LAY_ON_HANDS: (3, 3, Subclass.PALADIN),
    Talent.AURA_OF_PROTECTION: (3, 3, Subclass.PALADIN),
    Talent.WALL_OF_LIGHT: (3, 3, Subclass.PALADIN),
    # Armor ability unlocking talents
    Talent.ASCENDED_FORM_ABILITY: (1, 3, None),
    Talent.TRINITY_ABILITY: (1, 3, None),
    Talent.POWER_OF_MANY_ABILITY: (1, 3, None),
    # Tier 4 — Ascended Form
    Talent.DIVINE_INTERVENTION: (4, 4, None),
    Talent.JUDGEMENT: (4, 4, None),
    Talent.FLASH: (4, 4, None),
    # Tier 4 — Trinity
    Talent.BODY_FORM: (4, 4, None),
    Talent.MIND_FORM: (4, 4, None),
    Talent.SPIRIT_FORM: (4, 4, None),
    # Tier 4 — Power of Many
    Talent.BEAMING_RAY: (4, 4, None),
    Talent.LIFE_LINK: (4, 4, None),
    Talent.STASIS: (4, 4, None),
}

CLERIC_TALENT_CLASS_REQ: Dict[str, str] = {
    Talent.SATIATED_SPELLS: "cleric",
    Talent.HOLY_INTUITION: "cleric",
    Talent.SEARING_LIGHT: "cleric",
    Talent.SHIELD_OF_LIGHT: "cleric",
    Talent.ENLIGHTENING_MEAL: "cleric",
    Talent.RECALL_INSCRIPTION: "cleric",
    Talent.SUNRAY: "cleric",
    Talent.DIVINE_SENSE: "cleric",
    Talent.BLESS: "cleric",
    Talent.CLEANSE: "cleric",
    Talent.LIGHT_READING: "cleric",
    Talent.HOLY_LANCE: "cleric",
    Talent.HALLOWED_GROUND: "cleric",
    Talent.MNEMONIC_PRAYER: "cleric",
    Talent.LAY_ON_HANDS: "cleric",
    Talent.AURA_OF_PROTECTION: "cleric",
    Talent.WALL_OF_LIGHT: "cleric",
    Talent.ASCENDED_FORM_ABILITY: "cleric",
    Talent.TRINITY_ABILITY: "cleric",
    Talent.POWER_OF_MANY_ABILITY: "cleric",
    Talent.DIVINE_INTERVENTION: "cleric",
    Talent.JUDGEMENT: "cleric",
    Talent.FLASH: "cleric",
    Talent.BODY_FORM: "cleric",
    Talent.MIND_FORM: "cleric",
    Talent.SPIRIT_FORM: "cleric",
    Talent.BEAMING_RAY: "cleric",
    Talent.LIFE_LINK: "cleric",
    Talent.STASIS: "cleric",
}

CLERIC_TALENT_TITLES: Dict[str, str] = {
    Talent.SATIATED_SPELLS: "Satiated Spells",
    Talent.HOLY_INTUITION: "Holy Intuition",
    Talent.SEARING_LIGHT: "Searing Light",
    Talent.SHIELD_OF_LIGHT: "Shield of Light",
    Talent.ENLIGHTENING_MEAL: "Enlightening Meal",
    Talent.RECALL_INSCRIPTION: "Recall Inscription",
    Talent.SUNRAY: "Sunray",
    Talent.DIVINE_SENSE: "Divine Sense",
    Talent.BLESS: "Bless",
    Talent.CLEANSE: "Cleanse",
    Talent.LIGHT_READING: "Light Reading",
    Talent.HOLY_LANCE: "Holy Lance",
    Talent.HALLOWED_GROUND: "Hallowed Ground",
    Talent.MNEMONIC_PRAYER: "Mnemonic Prayer",
    Talent.LAY_ON_HANDS: "Lay on Hands",
    Talent.AURA_OF_PROTECTION: "Aura of Protection",
    Talent.WALL_OF_LIGHT: "Wall of Light",
    Talent.ASCENDED_FORM_ABILITY: "Ascended Form",
    Talent.TRINITY_ABILITY: "Trinity",
    Talent.POWER_OF_MANY_ABILITY: "Power of Many",
    Talent.DIVINE_INTERVENTION: "Divine Intervention",
    Talent.JUDGEMENT: "Judgement",
    Talent.FLASH: "Flash",
    Talent.BODY_FORM: "Body Form",
    Talent.MIND_FORM: "Mind Form",
    Talent.SPIRIT_FORM: "Spirit Form",
    Talent.BEAMING_RAY: "Beaming Ray",
    Talent.LIFE_LINK: "Life Link",
    Talent.STASIS: "Stasis",
}

CLERIC_TALENT_DESCRIPTIONS: Dict[str, str] = {
    Talent.SATIATED_SPELLS: "Eating food grants 3/5 barrier upon casting your next spell (and to your life-linked ally).",
    Talent.HOLY_INTUITION: "Unlocks the Holy Intuition spell, which reveals if an item is cursed for 3/2 charges.",
    Talent.SEARING_LIGHT: "Physical attacks against Illuminated targets deal +3/+5 bonus damage.",
    Talent.SHIELD_OF_LIGHT: "Unlocks the Shield of Light spell, absorbing 2-4/3-6 damage from a targeted enemy.",
    Talent.ENLIGHTENING_MEAL: "Eating food takes 1 turn and directly adds 0.67/1.0 charge to your Holy Tome.",
    Talent.RECALL_INSCRIPTION: "Unlocks the Recall Inscription spell, allowing you to recast the last used runestone or scroll within 10/300 turns.",
    Talent.SUNRAY: "Unlocks the Sunray spell, blasting an enemy for 4-8/6-12 magic damage (max against Undead/Demons) and blinding them for 4/6 turns.",
    Talent.DIVINE_SENSE: "Unlocks the Divine Sense spell, granting Mind Vision in an 8/12 tile radius for 50 turns.",
    Talent.BLESS: "Unlocks the Bless spell, granting Bless and barrier to yourself, or Bless and healing to an ally.",
    Talent.CLEANSE: "Unlocks the Cleanse spell, clearing all negative effects from yourself and allies, granting 10/20/30 barrier and 0/3/5 turns of debuff immunity.",
    Talent.LIGHT_READING: "Allows you to use the Holy Tome while unequipped in your backpack, recharging at 25%/50%/75% speed.",
    Talent.HOLY_LANCE: "Unlocks the Holy Lance spell, piercing enemies in a line for 30-55/45-83/60-110 damage.",
    Talent.HALLOWED_GROUND: "Unlocks the Hallowed Ground spell, creating a 3x3/5x5/7x7 sacred field that heals allies, roots enemies on cast, and cripples enemies.",
    Talent.MNEMONIC_PRAYER: "Unlocks the Mnemonic Prayer spell, extending active buffs on allies or debuffs on enemies by 3/4/5 turns.",
    Talent.LAY_ON_HANDS: "Unlocks the Lay on Hands spell, granting 15/20/25 barrier to yourself or 15/20/25 healing to an adjacent ally.",
    Talent.AURA_OF_PROTECTION: "Unlocks the Aura of Protection spell for 20 turns, reducing damage taken by allies within 2 tiles by 20%/30%/40% and sharing your armor glyph.",
    Talent.WALL_OF_LIGHT: "Unlocks the Wall of Light spell, raising a 3/5/7 tile wide barrier of solid light for 20 turns that knocks back and stuns enemies.",
    Talent.ASCENDED_FORM_ABILITY: "Unlocks Ascended Form, boosting all holy spells and granting a large shield.",
    Talent.TRINITY_ABILITY: "Unlocks Trinity, borrowing divine item powers in combat.",
    Talent.POWER_OF_MANY_ABILITY: "Unlocks Power of Many, summoning a radiant Light Ally.",
    Talent.DIVINE_INTERVENTION: "Unlocks the Divine Intervention spell during Ascended Form, granting 150/200/250/300 shielding and extending Ascended Form by 3/4/5/6 turns.",
    Talent.JUDGEMENT: "Unlocks the Judgement spell during Ascended Form, smiting all visible enemies for 10-20/15-30/20-40/25-50 base damage (+33.3% per spell cast).",
    Talent.FLASH: "Unlocks the Flash spell during Ascended Form, teleporting up to 3/4/5/6 tiles away.",
    Talent.BODY_FORM: "Unlocks the Body Form spell, imbuing a chosen weapon enchantment or armor glyph for 20/27/33/40 turns.",
    Talent.MIND_FORM: "Unlocks the Mind Form spell, casting an identified wand or throwing weapon at +3/+4/+5/+6 level.",
    Talent.SPIRIT_FORM: "Unlocks the Spirit Form spell, granting an identified ring's effect at +1/+2/+3/+4 or artifact power at +4/+6/+8/+10.",
    Talent.BEAMING_RAY: "Unlocks the Beaming Ray spell, teleporting your Light Ally up to 4/8/12/16 tiles and boosting their damage by +35%/+40%/+45%/+50%.",
    Talent.LIFE_LINK: "Unlocks the Life Link spell, splitting damage 50/50 with your Light Ally for 10/13/17/20 turns and duplicating cleric spells.",
    Talent.STASIS: "Unlocks the Stasis spell, safely storing your Light Ally inside you for up to 60/90/120/150 turns.",
}
