import {
  FRAME_W,
  FRAME_H,
  SCORPIO_FW,
  GNOLL_FW,
  GNOLL_FH,
  SHAMAN_FW,
  SHAMAN_FH,
  SNAKE_FW,
  SNAKE_FH,
  SNAKE_DEST,
  SKELETON_FW,
  SKELETON_FH,
  SKELETON_DEST,
  THIEF_FW,
  THIEF_FH,
  THIEF_DEST,
  DM100_FW,
  DM100_FH,
  DM100_DEST,
  DM200_FW,
  DM200_FH,
  DM200_DEST,
  GUARD_FW,
  GUARD_FH,
  GUARD_DEST,
  GOO_FW,
  GOO_FH,
  GOO_DEST,
  SLIME_FW,
  SLIME_FH,
  SLIME_DEST,
  WRAITH_FW,
  WRAITH_FH,
  WRAITH_DEST,
  PIRANHA_FW,
  PIRANHA_FH,
  PIRANHA_DEST,
  STATUE_FW,
  STATUE_FH,
  STATUE_DEST,
  GHOUL_FW,
  GHOUL_FH,
  GHOUL_DEST,
  MONK_FW,
  MONK_FH,
  MONK_DEST,
  WARLOCK_FW,
  WARLOCK_FH,
  WARLOCK_DEST,
  GOLEM_FW,
  GOLEM_FH,
  GOLEM_DEST,
  YOG_FW,
  YOG_FH,
  YOG_DEST,
  FIST_FW,
  FIST_FH,
  FIST_DEST,
  EYE_FW,
  EYE_FH,
  EYE_DEST,
  RIPPER_FW,
  RIPPER_FH,
  RIPPER_DEST,
  PYLON_FW,
  PYLON_FH,
  PYLON_DEST,
  TENGU_FW,
  TENGU_FH,
  TENGU_DEST,
  DM300_FW,
  DM300_FH,
  DM300_DEST,
  BRUTE_FW,
  BRUTE_FH,
  BRUTE_DEST,
  SWARM_FW,
  SWARM_FH,
  SWARM_DEST,
  KEEPER_FW,
  KEEPER_FH,
  KEEPER_DEST,
  SHEEP_FW,
  SHEEP_FH,
  SHEEP_DEST,
  IMP_FW,
  IMP_FH,
  IMP_DEST,
  WANDMAKER_FW,
  WANDMAKER_FH,
  WANDMAKER_DEST,
  ROT_HEART_FW,
  ROT_HEART_FH,
  ROT_HEART_DEST,
  ROT_LASHER_FW,
  ROT_LASHER_FH,
  ROT_LASHER_DEST,
  NEWBORN_ELEMENTAL_FW,
  NEWBORN_ELEMENTAL_FH,
  NEWBORN_ELEMENTAL_DEST,
  RATKING_FW,
  RATKING_FH,
  RATKING_DEST,
  GHOST_FW,
  GHOST_FH,
  GHOST_DEST,
  SUCCUBUS_FW,
  SUCCUBUS_FH,
  SUCCUBUS_DEST,
  getBanditFrame,
  getBeeFrame,
  getBruteFrame,
  getCrabFrame,
  getDM100Frame,
  getDM200Frame,
  getDM300Frame,
  getEyeFrame,
  getFetidRatFrame,
  getFistFrame,
  getGhostFrame,
  getGnollFrame,
  getGnollTricksterFrame,
  getGooFrame,
  getGolemFrame,
  getGreatCrabFrame,
  getGuardFrame,
  getHermitCrabFrame,
  getImpFrame,
  getKeeperFrame,
  getMimicFrame,
  getMonkFrame,
  getNecromancerFrame,
  getNewbornElementalFrame,
  getPiranhaFrame,
  getPylonFrame,
  getRatFrame,
  getRatKingFrame,
  getRipperFrame,
  getRotHeartFrame,
  getRotLasherFrame,
  getScorpioFrame,
  getSheepFrame,
  getShamanFrame,
  getSkeletonFrame,
  getSlimeFrame,
  getSnakeFrame,
  getSpawnerFrame,
  getSpinnerFrame,
  getStatueFrame,
  getSuccubusFrame,
  getSwarmFrame,
  getTenguFrame,
  getThiefFrame,
  getWandmakerFrame,
  getWarlockFrame,
  getWraithFrame,
  getYogFrame,
} from './mobs';

// Gnoll's 12x15 frame, centered/bottom-aligned in the 32px tile per SPD placement
// (x=(col+0.5)*16-w/2, y=(row+1)*16-h), scaled 2x -> 24x30 at offset (+4,+2).
export const GNOLL_DEST = { dx: 4, dy: 2, dw: 24, dh: 30 };
export const SHAMAN_DEST = { dx: 4, dy: 2, dw: 24, dh: 30 };

// A few sheets stack several mob variants in fixed-height rows rather than
// giving each variant its own image. Each variant gets a row index and the row
// pitch its frames are laid out at.
const SHAMAN_ROWS = { 'Red Shaman': 0, 'Blue Shaman': 1, 'Purple Shaman': 2 };
const FIST_ROWS = {
  'Burning Fist': 0,
  'Soiled Fist': 1,
  'Rotting Fist': 2,
  'Rusted Fist': 3,
  'Bright Fist': 4,
  'Dark Fist': 5,
};
const MIMIC_ROWS = { Mimic: 0, 'Golden Mimic': 1, 'Crystal Mimic': 2, 'Ebony Mimic': 3 };

// mob.name -> sprite descriptor.
//   key        atlas entry on assetImages
//   frame      (mob, mobAnim, now) => horizontal frame offset, or null for a static sheet
//   fw / fh    source frame size, default the full 16x16 tile
//   dest       in-tile placement for sheets whose native frame is smaller than a tile
//   row / rowH atlas row offset, either a literal index or (mob) => index
//   brightness (mob) => filter multiplier (NecroSkeleton tints itself in SPD)
//   blend      ctx.globalCompositeOperation override
//   alpha      globalAlpha override applied alongside blend
const MOB_SPRITES = {
  // Sewers
  'Rat': { key: 'rat', frame: getRatFrame },
  'Fetid Rat': { key: 'rat', frame: getFetidRatFrame, row: 2, rowH: FRAME_H },
  'Crab': { key: 'crab', frame: getCrabFrame },
  'Hermit Crab': { key: 'crab', frame: getHermitCrabFrame, row: 1, rowH: FRAME_H },
  'Great Crab': { key: 'crab', frame: getGreatCrabFrame, row: 2, rowH: FRAME_H },
  'Slime': { key: 'slime', frame: getSlimeFrame, fw: SLIME_FW, fh: SLIME_FH, dest: SLIME_DEST },
  'Caustic Slime': {
    key: 'slime', frame: getSlimeFrame, fw: SLIME_FW, fh: SLIME_FH, dest: SLIME_DEST, row: 1, rowH: SLIME_FH,
  },
  'Snake': { key: 'snake', frame: getSnakeFrame, fw: SNAKE_FW, fh: SNAKE_FH, dest: SNAKE_DEST },
  'Gnoll': { key: 'gnoll', frame: getGnollFrame, fw: GNOLL_FW, fh: GNOLL_FH, dest: GNOLL_DEST },
  'Gnoll Trickster': { key: 'gnoll', frame: getGnollTricksterFrame, fw: GNOLL_FW, fh: GNOLL_FH, dest: GNOLL_DEST, row: 2, rowH: GNOLL_FH },
  'Red Shaman': { key: 'shaman', frame: getShamanFrame, fw: SHAMAN_FW, fh: SHAMAN_FH, dest: SHAMAN_DEST, row: SHAMAN_ROWS['Red Shaman'], rowH: SHAMAN_FH },
  'Blue Shaman': { key: 'shaman', frame: getShamanFrame, fw: SHAMAN_FW, fh: SHAMAN_FH, dest: SHAMAN_DEST, row: SHAMAN_ROWS['Blue Shaman'], rowH: SHAMAN_FH },
  'Purple Shaman': { key: 'shaman', frame: getShamanFrame, fw: SHAMAN_FW, fh: SHAMAN_FH, dest: SHAMAN_DEST, row: SHAMAN_ROWS['Purple Shaman'], rowH: SHAMAN_FH },
  'Scorpio': { key: 'scorpio', frame: getScorpioFrame, fw: SCORPIO_FW, fh: SCORPIO_FW },
  'Yog Scorpio': { key: 'scorpio', frame: getScorpioFrame, fw: SCORPIO_FW, fh: SCORPIO_FW },
  'Swarm': { key: 'swarm', frame: getSwarmFrame, fw: SWARM_FW, fh: SWARM_FH, dest: SWARM_DEST },
  'Bat': { key: 'bat' },
  'Sentry': { key: 'sentry' },
  'Bee': { key: 'bee', frame: getBeeFrame },
  'Spinner': { key: 'spinner', frame: getSpinnerFrame },
  'Sheep': { key: 'sheep', frame: getSheepFrame, fw: SHEEP_FW, fh: SHEEP_FH, dest: SHEEP_DEST },
  'Statue': { key: 'statue', frame: getStatueFrame, fw: STATUE_FW, fh: STATUE_FH, dest: STATUE_DEST },
  'Armored Statue': { key: 'statue', frame: getStatueFrame, fw: STATUE_FW, fh: STATUE_FH, dest: STATUE_DEST, row: 1, rowH: FRAME_H },
  'Thief': { key: 'thief', frame: getThiefFrame, fw: THIEF_FW, fh: THIEF_FH, dest: THIEF_DEST },
  'Bandit': { key: 'thief', frame: getBanditFrame, fw: THIEF_FW, fh: THIEF_FH, dest: THIEF_DEST },
  'Mimic': { key: 'mimic', frame: getMimicFrame, row: MIMIC_ROWS.Mimic, rowH: FRAME_H },
  'Golden Mimic': { key: 'mimic', frame: getMimicFrame, row: MIMIC_ROWS['Golden Mimic'], rowH: FRAME_H },
  'Crystal Mimic': { key: 'mimic', frame: getMimicFrame, row: MIMIC_ROWS['Crystal Mimic'], rowH: FRAME_H },
  'Ebony Mimic': { key: 'mimic', frame: getMimicFrame, row: MIMIC_ROWS['Ebony Mimic'], rowH: FRAME_H },

  // Prison
  'Skeleton': { key: 'skeleton', frame: getSkeletonFrame, fw: SKELETON_FW, fh: SKELETON_FH, dest: SKELETON_DEST },
  'NecroSkeleton': {
    key: 'skeleton', frame: getSkeletonFrame, fw: SKELETON_FW, fh: SKELETON_FH, dest: SKELETON_DEST,
    brightness: (mob) => (mob.tinted ? 0.75 : 1),
  },
  'DM-100': { key: 'dm100', frame: getDM100Frame, fw: DM100_FW, fh: DM100_FH, dest: DM100_DEST },
  'DM-200': { key: 'dm200', frame: getDM200Frame, fw: DM200_FW, fh: DM200_FH, dest: DM200_DEST },
  'DM-201': { key: 'dm200', frame: getDM200Frame, fw: DM200_FW, fh: DM200_FH, dest: DM200_DEST },
  'Guard': { key: 'guard', frame: getGuardFrame, fw: GUARD_FW, fh: GUARD_FH, dest: GUARD_DEST },
  'Necromancer': { key: 'necromancer', frame: getNecromancerFrame },
  'Wraith': { key: 'wraith', frame: getWraithFrame, fw: WRAITH_FW, fh: WRAITH_FH, dest: WRAITH_DEST },
  'Tormented Spirit': { key: 'wraith', frame: getWraithFrame, fw: WRAITH_FW, fh: WRAITH_FH, dest: WRAITH_DEST },
  'Dust Wraith': { key: 'wraith', frame: getWraithFrame, fw: WRAITH_FW, fh: WRAITH_FH, dest: WRAITH_DEST },
  'Piranha': { key: 'piranha', frame: getPiranhaFrame, fw: PIRANHA_FW, fh: PIRANHA_FH, dest: PIRANHA_DEST },
  'Phantom Piranha': { key: 'piranha', frame: getPiranhaFrame, fw: PIRANHA_FW, fh: PIRANHA_FH, dest: PIRANHA_DEST, row: 1, rowH: FRAME_H },
  'Goo': { key: 'goo', frame: getGooFrame, fw: GOO_FW, fh: GOO_FH, dest: GOO_DEST },

  // Caves
  'Ghost': { key: 'ghost', frame: getGhostFrame, fw: GHOST_FW, fh: GHOST_FH, dest: GHOST_DEST, blend: 'lighter', alpha: 0.85 },
  'Ghost Hero': { key: 'ghost', frame: getGhostFrame, fw: GHOST_FW, fh: GHOST_FH, dest: GHOST_DEST, blend: 'lighter', alpha: 0.85 },
  'Succubus': { key: 'succubus', frame: getSuccubusFrame, fw: SUCCUBUS_FW, fh: SUCCUBUS_FH, dest: SUCCUBUS_DEST },
  'Dwarf King': { key: 'king', frame: getDwarfKingFrame },
  'Demon Spawner': { key: 'spawner', frame: getSpawnerFrame },

  // City
  'Ghoul': { key: 'ghoul', frame: getGhoulFrame, fw: GHOUL_FW, fh: GHOUL_FH, dest: GHOUL_DEST },
  'DK Ghoul': { key: 'ghoul', frame: getGhoulFrame, fw: GHOUL_FW, fh: GHOUL_FH, dest: GHOUL_DEST },
  'DK Monk': { key: 'monk', frame: getMonkFrame, fw: MONK_FW, fh: MONK_FH, dest: MONK_DEST },
  'Warlock': { key: 'warlock', frame: getWarlockFrame, fw: WARLOCK_FW, fh: WARLOCK_FH, dest: WARLOCK_DEST },
  'DK Warlock': { key: 'warlock', frame: getWarlockFrame, fw: WARLOCK_FW, fh: WARLOCK_FH, dest: WARLOCK_DEST },
  'Brute': { key: 'brute', frame: getBruteFrame, fw: BRUTE_FW, fh: BRUTE_FH, dest: BRUTE_DEST },
  'Armored Brute': { key: 'brute', frame: getBruteFrame, fw: BRUTE_FW, fh: BRUTE_FH, dest: BRUTE_DEST, row: 1, rowH: BRUTE_FH },
  'Tengu': { key: 'tengu', frame: getTenguFrame, fw: TENGU_FW, fh: TENGU_FH, dest: TENGU_DEST },

  // Halls
  'Yog-Dzewa': { key: 'yog', frame: getYogFrame, fw: YOG_FW, fh: YOG_FH, dest: YOG_DEST },
  'Yog Ripper': { key: 'ripper', frame: getRipperFrame, fw: RIPPER_FW, fh: RIPPER_FH, dest: RIPPER_DEST },
  'Ripper Demon': { key: 'ripper', frame: getRipperFrame, fw: RIPPER_FW, fh: RIPPER_FH, dest: RIPPER_DEST },
  'Evil Eye': { key: 'eye', frame: getEyeFrame, fw: EYE_FW, fh: EYE_FH, dest: EYE_DEST },
  'Yog Eye': { key: 'eye', frame: getEyeFrame, fw: EYE_FW, fh: EYE_FH, dest: EYE_DEST },
  'Golem': { key: 'golem', frame: getGolemFrame, fw: GOLEM_FW, fh: GOLEM_FH, dest: GOLEM_DEST },
  'DK Golem': { key: 'golem', frame: getGolemFrame, fw: GOLEM_FW, fh: GOLEM_FH, dest: GOLEM_DEST },
  'Rot Heart': { key: 'rotHeart', frame: getRotHeartFrame, fw: ROT_HEART_FW, fh: ROT_HEART_FH, dest: ROT_HEART_DEST },
  'Rot Lasher': { key: 'rotLasher', frame: getRotLasherFrame, fw: ROT_LASHER_FW, fh: ROT_LASHER_FH, dest: ROT_LASHER_DEST },
  'Newborn Fire Elemental': { key: 'elemental', frame: getNewbornElementalFrame, fw: NEWBORN_ELEMENTAL_FW, fh: NEWBORN_ELEMENTAL_FH, dest: NEWBORN_ELEMENTAL_DEST },
  'Rat King': { key: 'ratking', frame: getRatKingFrame, fw: RATKING_FW, fh: RATKING_FH, dest: RATKING_DEST },
  'DM-300': { key: 'dm300', frame: getDM300Frame, fw: DM300_FW, fh: DM300_FH, dest: DM300_DEST, row: (mob) => (mob.supercharged ? 1 : 0), rowH: DM300_FH },

  // NPCs
  'Shopkeeper': { key: 'shopkeeper', frame: getKeeperFrame, fw: KEEPER_FW, fh: KEEPER_FH, dest: KEEPER_DEST },
  'Imp': { key: 'imp', frame: getImpFrame, fw: IMP_FW, fh: IMP_FH, dest: IMP_DEST },
  'Wandmaker': { key: 'wandmaker', frame: getWandmakerFrame, fw: WANDMAKER_FW, fh: WANDMAKER_FH, dest: WANDMAKER_DEST },
};

// Yog's fists all share yog_fists.png, one variant per FIST_FH-tall row.
for (const [name, row] of Object.entries(FIST_ROWS)) {
  MOB_SPRITES[name] = { key: 'fists', frame: getFistFrame, fw: FIST_FW, fh: FIST_FH, dest: FIST_DEST, row, rowH: FIST_FH };
}

const resolveRow = (row, mob) => (typeof row === 'function' ? row(mob) : (row || 0));

// Everything the mob renderer needs to blit one mob: the source rect inside the
// atlas sheet (sx/sy/fw/fh) and where to put it inside the 32px tile (dest).
// Unknown names fall back to the rat, matching the old draw path.
export function resolveMobSprite(mob, assetImages, mobAnim = {}, now = 0) {
  const spec = MOB_SPRITES[mob?.name] || MOB_SPRITES.Rat;
  return {
    img: assetImages?.[spec.key] || null,
    sx: spec.frame ? spec.frame(mob, mobAnim, now) : 0,
    sy: spec.row ? resolveRow(spec.row, mob) * spec.rowH : 0,
    fw: spec.fw || FRAME_W,
    fh: spec.fh || FRAME_H,
    dest: spec.dest || null,
    brightness: spec.brightness ? spec.brightness(mob) : 1,
    blend: spec.blend || null,
    alpha: spec.alpha ?? 1,
  };
}

export const MOB_SHEET_ROWS = { SHAMAN_ROWS, FIST_ROWS, MIMIC_ROWS, tileDest };
