HEARTY_MEAL_THRESHOLD = 0.334
HEARTY_MEAL_BASE_HEAL = 2
HEARTY_MEAL_HEAL_PER_LEVEL = 2

IRON_STOMACH_IMMUNITY_DURATION_PER_LEVEL = 20.0

LIQUID_WILLPOWER_BASE_RATIO = 0.030
LIQUID_WILLPOWER_RATIO_PER_LEVEL = 0.035
LIQUID_WILLPOWER_SHIELD_DECAY = 300

STRONGMAN_BASE_BONUS = 0.03
STRONGMAN_BONUS_PER_LEVEL = 0.05

CACHED_RATIONS_BASE_HEAL = 4
CACHED_RATIONS_HEAL_PER_LEVEL = 4
SPEEDY_STEALTH_SPEED_MULT = 2.0
MOMENTUM_MAX = 10

EMPOWERING_MEAL_CHARGES = 3

ENERGIZING_MEAL_BASE_DURATION = 2.0
ENERGIZING_MEAL_DURATION_PER_LEVEL = 3.0

SOUL_EATER_BASE_HEAL = 2
SOUL_EATER_HEAL_PER_LEVEL = 2

INVIGORATING_MEAL_BASE_DURATION = 5.0
INVIGORATING_MEAL_DURATION_PER_LEVEL = 5.0

FARSIGHT_VIEW_BONUS_PER_LEVEL = 2
REJUVENATING_STEPS_HEAL_PER_LEVEL = 1

# Cleric constants
SATIATED_SPELLS_BASE_SHIELD = 1
SATIATED_SPELLS_SHIELD_PER_LEVEL = 2
SEARING_LIGHT_BONUS_DMG = [0, 3, 5]
SHIELD_OF_LIGHT_TURNS = 5.0
DIVINE_SENSE_DURATION = 50.0
AURA_OF_PROTECTION_DURATION = 20.0
WALL_OF_LIGHT_DURATION = 20.0
HALLOWED_GROUND_DURATION = 20.0

